name: Docker

on:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push the images
        run: |
          tmpName="image-$RANDOM"
          docker build --tag $tmpName --build-arg ACTIVEMQ_VERSION=${{ secrets.ACTIVEMQ_VERSION }} .
          IMAGE_ID=${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}
          docker tag $tmpName $IMAGE_ID:${{ secrets.ACTIVEMQ_VERSION }}
          docker push $IMAGE_ID:${{ secrets.ACTIVEMQ_VERSION }}
          docker tag $tmpName $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
